

Stack = function() {
	this.mystack = new Array()
}

Stack.prototype.push = function(x) {
	this.mystack.push(x)
}

Stack.prototype.pop = function() {
	return this.mystack.pop()
}

Stack.prototype.peek = function() {
    return this.mystack[this.mystack.length-1]
}

z = new Stack()
z.push(10)
z.push([1,2,3])
z.push(20)


function oneDifferent(word1,word2) {
    var diffs = 0;
    for (var i = 0; i < word1.length; i++) {
        if (word1.charAt(i) != word2.charAt(i)) {
            diffs = diffs + 1;
        }
    }
    if (diffs == 1) {
        return true;
    } else {
        return false;
    }
}    

used = {};
function findAllOneDifferent(word,wlist,used) {
    var res = new Array()
    for (var w in wlist) {
        if (oneDifferent(word,wlist[w]) && ! (wlist[w] in used) )
            res.push(wlist[w]);
    }
    //res.sort(sortByDist)
    return res
}

function compGoal(w) {
    var ct = 0;
    for (var i = 0; i < w.length; i++) {
        if (w[i] == end[i]) ct++;
    }
    return ct;
}
function sortByDist(w1,w2) {
// use end as global...
    var x = compGoal(w1);
    var y = compGoal(w2);
    return x-y
}

function createStacks(currentStack,queue,used,goal,wlist) {
    newWords = findAllOneDifferent(currentStack[0],wlist,used)
    for (var i in newWords) {
        newStack = currentStack.slice();
        newStack.unshift(newWords[i])
        used[newWords[i]] = true
        if (newWords[i] == goal) {
            return newStack
        } else {
            queue.push(newStack)
        }
    }
    return false;
    
}


threeLetterWords = [ 'aln', 'alo', 'all', 'rok', 'alk', 'ore', 'roi', 'alf', 'pep', 'edh',
'ale', 'alb', 'edo', 'vug', 'ala', 'rox', 'roy', 'ugh', 'per', 'aly',
'ric', 'alt', 'ose', 'alp', 'row', 'ume', 'vet', 'ron', 'auh', 'auk',
'vow', 'aum', 'pen', 'vee', 'aus', 'tji', 'saw', 'goy', 'rob', 'vei',
'orc', 'fay', 'lox', 'far', 'rod', 'fat', 'roe', 'hak', 'tue', 'fan',
'taj', 'fam', 'rog', 'fag', 'fad', 'fae', 'tri', 'dim', 'din', 'peg',
'gue', 'gud', 'did', 'die', 'dig', 'zag', 'eve', 'dib', 'gul', 'gus',
'gur', 'gup', 'red', 'gut', 'dit', 'guz', 'div', 'ree', 'dip', 'uds',
'dis', 'pul', 'odz', 'wab', 'ten', 'caw', 'noa', 'ods', 'mwa', 'tee',
'mrs', 'teg', 'tez', 'oda', 'dew', 'odd', 'ode', 'uca', 'tew', 'aba',
'abb', 'sud', 'abe', 'nei', 'nef', 'rot', 'ned', 'han', 'neb', 'sui',
'abo', 'rub', 'suu', 'sus', 'abu', 'kui', 'sup', 'zig', 'aby', 'net',
'zea', 'suz', 'kua', 'can', 'lea', 'meg', 'rua', 'led', 'den', 'sri',
'leg', 'mem', 'hao', 'meo', 'lek', 'ush', 'len', 'leo', 'met', 'ler',
'les', 'let', 'leu', 'lev', 'lew', 'ivy', 'ley', 'yan', 'dry', 'boy',
'woy', 'zac', 'yis', 'bop', 'eke', 'bos', 'bot', 'aku', 'bow', 'wea',
'ako', 'bom', 'bon', 'boo', 'boa', 'aka', 'deg', 'bod', 'ake', 'bog',
'wig', 'vic', 'via', 'sat', 'spy', 'win', 'wim', 'apt', 'vim', 'orf',
'vip', 'taw', 'wis', 'vex', 'apa', 'wiz', 'bra', 'ape', 'cha', 'fed',
'fee', 'eye', 'che', 'zip', 'fen', 'chi', 'twi', 'ull', 'hem', 'eyn',
'few', 'fet', 'feu', 'lwo', 'ayu', 'toy', 'ora', 'fez', 'fey', 'ulu',
'web', 'had', 'fly', 'dey', 'cay', 'err', 'ers', 'car', 'cap', 'flu',
'dev', 'cat', 'erd', 'ere', 'erg', 'del', 'era', 'flo', 'cal', 'cab',
'deb', 'ula', 'cag', 'dee', 'cad', 'tat', 'hip', 'tav', 'obe', 'tap',
'tar', 'kyl', 'pie', 'wed', 'tax', 'tay', 'tad', 'tae', 'tag', 'sly',
'tab', 'rig', 'tal', 'spa', 'mel', 'ist', 'tai', 'kyu', 'sis', 'hog',
'hod', 'hoe', 'end', 'ido', 'hon', 'rye', 'hoi', 'sic', 'how', 'hot',
'ens', 'sig', 'low', 'hop', 'sid', 'aft', 'sin', 'hox', 'hoy', 'lam',
'lan', 'lao', 'mau', 'lai', 'maw', 'lak', 'lad', 'max', 'reh', 'lag',
'lab', 'lac', 'ory', 'mac', 'mab', 'lax', 'lay', 'laz', 'lat', 'hob',
'law', 'lap', 'mal', 'lar', 'las', 'rud', 'kra', 'van', 'sit', 'ego',
'egg', 'ito', 'six', 'zed', 'wut', 'wit', 'zen', 'zel', 'ita', 'zer',
'pow', 'zep', 'own', 'dha', 'wud', 'uva', 'yow', 'its', 'zak', 'fir',
'jig', 'fip', 'jib', 'sog', 'fit', 'sib', 'imi', 'wat', 'fix', 'jim',
'sia', 'him', 'fib', 'imp', 'pac', 'imu', 'cly', 'fid', 'fie', 'oar',
'tst', 'bye', 'fin', 'wry', 'dad', 'dae', 'cee', 'dag', 'wir', 'sie',
'dab', 'upo', 'dal', 'dam', 'dan', 'dao', 'dah', 'aes', 'nob', 'dak',
'oka', 'daw', 'dap', 'noy', 'dar', 'cep', 'not', 'nou', 'now', 'day',
'nor', 'oxy', 'yon', 'tow', 'taa', 'loy', 'hin', 'rio', 'ife', 'val',
'sim', 'man', 'eva', 'luc', 'out', 'sow', 'map', 'sov', 'mas', 'gun',
'mar', 'gum', 'sob', 'our', 'pot', 'mat', 'gol', 'goo', 'gon', 'goi',
'oii', 'sha', 'mew', 'god', 'gog', 'syd', 'goa', 'ret', 'gob', 'may',
'blo', 'cwm', 'nye', 'rel', 'reb', 'got', 'rea', 'ref', 'reg', 'gos',
'gor', 'ass', 'lob', 'pun', 'asp', 'mev', 'ast', 'pud', 'ort', 'pug',
'pua', 'pub', 'qua', 'nth', 'asa', 'hew', 'ase', 'sla', 'ask', 'lof',
'ash', 'orb', 'guy', 'pur', 'kol', 'sur', 'ate', 'lod', 'ata', 'waw',
'yus', 'shu', 'put', 'ati', 'tor', 'ova', 'iso', 'ism', 'yun', 'mae',
'won', 'mad', 'zan', 'yin', 'mag', 'wac', 'zad', 'ona', 'owd', 'ute',
'loo', 'ihi', 'zax', 'mah', 'ons', 'zat', 'zar', 'ser', 'koi', 'yid',
'iao', 'ian', 'jew', 'jet', 'kon', 'koa', 'mam', 'top', 'kob', 'lop',
'tot', 'tou', 'toi', 'jef', 'mao', 'jed', 'tea', 'kop', 'kos', 'kor',
'kou', 'tog', 'mer', 'jem', 'hud', 'hue', 'cyp', 'tol', 'hub', 'gyn',
'gym', 'tom', 'huh', 'hui', 'huk', 'hut', 'fei', 'osc', 'hup', 'too',
'gyp', 'wod', 'udi', 'hen', 'mow', 'seg', 'ibo', 'ben', 'bel', 'aam',
'aal', 'bea', 'beg', 'bed', 'bee', 'stu', 'bey', 'tod', 'ber', 'bes',
'toe', 'sty', 'bet', 'and', 'rag', 'rad', 'sah', 'rab', 'ana', 'sam',
'sal', 'ran', 'sab', 'ann', 'ram', 'raj', 'ani', 'rah', 'sad', 'ant',
'raw', 'pip', 'hug', 'ras', 'rap', 'lui', 'sap', 'pry', 'any', 'rax',
'iba', 'lid', 'lie', 'lif', 'mim', 'mil', 'min', 'hyp', 'lin', 'mib',
'eft', 'mid', 'mig', 'pup', 'lit', 'mix', 'liv', 'lip', 'hum', 'new',
'mir', 'hun', 'liz', 'pyx', 'war', 'sol', 'kaf', 'iwa', 'neo', 'kaj',
'kai', 'tyg', 'kan', 'awn', 'awl', 'kaw', 'rho', 'kat', 'tyt', 'pya',
'awe', 'awd', 'rhe', 'why', 'awa', 'sub', 'urd', 'ure', 'lee', 'pus',
'don', 'ura', 'dol', 'dom', 'dob', 'doc', 'urn', 'uro', 'dog', 'dod',
'doe', 'uru', 'axe', 'dor', 'dos', 'dop', 'dow', 'dot', 'son', 'nee',
'toa', 'wur', 'suk', 'wob', 'wop', 'lum', 'wup', 'nea', 'one', 'och',
'ock', 'psi', 'jay', 'jaw', 'jat', 'zee', 'jar', 'woo', 'jap', 'bug',
'jan', 'yea', 'jam', 'jag', 'jab', 'oil', 'men', 'ges', 'ger', 'his',
'hit', 'get', 'ssu', 'gez', 'gey', 'lug', 'nep', 'hia', 'hic', 'ssi',
'hie', 'gee', 'ged', 'dye', 'lei', 'geo', 'gen', 'gem', 'gel', 'eme',
'baw', 'bat', 'aer', 'bar', 'bas', 'bap', 'yex', 'emm', 'shy', 'cry',
'utu', 'bay', 'emu', 'bag', 'bad', 'bae', 'bab', 'bac', 'baa', 'ban',
'shi', 'bal', 'bam', 'cro', 'bah', 'sho', 'sew', 'set', 'art', 'aru',
'ebb', 'ken', 'arx', 'ary', 'nut', 'sey', 'sex', 'nun', 'ara', 'nul',
'arc', 'sec', 'are', 'sea', 'poe', 'sen', 'wer', 'ark', 'nub', 'arm',
'arn', 'aro', 'soh', 'lur', 'lut', 'pst', 'mus', 'lux', 'wot', 'wow',
'mux', 'wun', 'tug', 'mud', 'mug', 'irk', 'yip', 'lue', 'use', 'kef',
'mum', 'ira', 'wog', 'mun', 'ire', 'luo', 'tux', 'ima', 'yez', 'jos',
'jot', 'jow', 'keg', 'joy', 'kee', 'ked', 'tut', 'keb', 'kea', 'tui',
'job', 'eli', 'joe', 'ike', 'jog', 'tua', 'tub', 'ket', 'ker', 'jon',
'ham', 'cop', 'cos', 'cor', 'loa', 'cot', 'cow', 'ila', 'coy', 'cox',
'ill', 'cup', 'ilk', 'wap', 'tau', 'jin', 'eta', 'coe', 'cod', 'cog',
'wro', 'phu', 'tra', 'wha', 'ski', 'col', 'coo', 'con', 'sak', 'key',
'pox', 'poy', 'elf', 'mru', 'kex', 'way', 'sai', 'pop', 'wen', 'pon',
'lex', 'pol', 'pik', 'wem', 'poh', 'poi', 'sao', 'pod', 'hag', 'pob',
'poa', 'fra', 'dum', 'dun', 'duo', 'swa', 'yat', 'dub', 'dud', 'add',
'yas', 'dug', 'dux', 'sac', 'yao', 'cud', 'yah', 'yak', 'dup', 'yad',
'fry', 'kep', 'pro', 'fig', 'zoa', 'gaz', 'gay', 'oto', 'gaw', 'sag',
'gau', 'gat', 'gas', 'gar', 'gap', 'gan', 'gam', 'gal', 'gaj', 'els',
'gag', 'yap', 'gad', 'gab', 'tox', 'sny', 'fut', 'fur', 'aix', 'gnu',
'ait', 'iyo', 'tip', 'rat', 'air', 'aim', 'ail', 'fud', 'sax', 'fub',
'fun', 'aid', 'fum', 'sma', 'bor', 'saj', 'bin', 'coz', 'iva', 'rix',
'vol', 'rit', 'non', 'rip', 'yam', 'mya', 'avo', 'rik', 'sar', 'ave',
'rid', 'rie', 'rib', 'ava', 'bis', 'ria', 'pap', 'par', 'pat', 'pau',
'paw', 'pax', 'pay', 'ewe', 'nod', 'vod', 'cob', 'pad', 'see', 'mor',
'pah', 'vag', 'dhu', 'ray', 'pal', 'pam', 'pan', 'phi', 'mop', 'pho',
'nil', 'nim', 'nib', 'bib', 'kip', 'nig', 'nid', 'kit', 'voe', 'ion',
'nix', 'sir', 'kin', 'kim', 'kil', 'yok', 'nip', 'tup', 'bob', 'nit',
'til', 'off', 'thy', 'she', 'try', 'ofo', 'tho', 'wye', 'uji', 'oft',
'lim', 'san', 'moo', 'the', 'yoe', 'tha', 'cam', 'yeo', 'yen', 'pyr',
'oak', 'das', 'vog', 'yed', 'oki', 'wid', 'tck', 'tch', 'tur', 'yep',
'yes', 'yer', 'yet', 'yew', 'hah', 'elk', 'nog', 'cut', 'hal', 'cur',
'ell', 'elm', 'elb', 'wei', 'vie', 'adz', 'tin', 'eld', 'ady', 'wes',
'hay', 'cue', 'ade', 'cub', 'ada', 'hap', 'ado', 'cum', 'hat', 'hau',
'elt', 'haw', 'ami', 'moy', 'bim', 'yoy', 'rev', 'ama', 'big', 'bid',
'lis', 'ame', 'mou', 'mot', 'amy', 'ope', 'moi', 'azo', 'biz', 'mon',
'mob', 'bit', 'mog', 'amt', 'moe', 'mod', 'mho', 'tig', 'vis', 'roc',
'una', 'eer', 'eel', 'ule', 'pom', 'yar', 'wyn', 'ust', 'two', 'vum',
'sum', 'old', 'ole', 'sue', 'sky', 'olm', 'saa', 'yuh', 'uke', 'ijo',
'fot', 'fou', 'fow', 'ess', 'ump', 'for', 'pet', 'pew', 'fox', 'foy',
'ice', 'pes', 'fod', 'foe', 'icy', 'fog', 'fob', 'tye', 'ped', 'pee',
'fon', 'foo', 'pea', 'who', 'run', 'rum', 'oes', 'oer', 'hsi', 'rug',
'ply', 'rue', 'rux', 'twa', 'woe', 'rus', 'rut', 'yot', 'zoo', 'ace',
'obi', 'ach', 'rim', 'kru', 'aye', 'act', 'wey', 'ide', 'yaw', 'ida',
'sip', 'owl', 'soc', 'aha', 'soe', 'sod', 'owk', 'owe', 'fro', 'sok',
'aho', 'due', 'sop', 'sou', 'sot', 'aht', 'ahu', 'soy', 'cho', 'kay',
'het', 'wan', 'git', 'hep', 'log', 'her', 'gip', 'wag', 'waf', 'wae',
'wad', 'hex', 'hey', 'gig', 'gif', 'gie', 'gid', 'gib', 'lot', 'lou',
'gio', 'gin', 'gim', 'gil', 'was', 'hei', 'vat', 'vau', 'buy', 'jug',
'jud', 'ean', 'bur', 'bus', 'opt', 'jun', 'urf', 'but', 'ouf', 'jur',
'bun', 'jut', 'bum', 'bub', 'sun', 'ear', 'eat', 'bud', 'tum', 'uta',
'cig', 'cid', 'sil', 'wet', 'cit', 'vai', 'say', 'tun', 'ohm', 'oho',
'pim', 'pin', 'lys', 'pia', 'pic', 'khu', 'pig', 'pix', 'lye', 'inn',
'ino', 'ink', 'ind', 'kha', 'pir', 'ing', 'pit', 'yee', 'wee', 'nab',
'oaf', 'yom', 'naa', 'grr', 'nag', 'yoi', 'nae', 'tit', 'nak', 'oam',
'uri', 'nan', 'nam', 'nar', 'tim', 'nap', 'oat', 'naw', 'nat', 'gra',
'tid', 'tie', 'you', 'nay', 'yor', 'tib', 'tic', 'tam', 'umu', 'urs',
'rex', 'mes', 'hwa', 'wah', 'ich', 'tec', 'udo', 'yox', 'fop', 'ubi',
'tan', 'ago', 'sye', 'age', 'ton', 'eon', 'aga', 'vas', 'ted', 'agy',
'quo', 'wax', 'tao', 'rep']

fiveLetterWords = [ 'xylem', 'jihad', 'aegis', 'woody', 'caner', 'canes', 'scold', 'caned', 'filar', 'bocks',
'digit', 'spacy', 'prize', 'woods', 'slews', 'knell', 'sooty', 'tired', 'bacon', 'pulse',
'soots', 'tires', 'rusty', 'sooth', 'shmoo', 'holon', 'rusts', 'pubis', 'burps', 'mrads',
'locos', 'decry', 'pawed', 'avers', 'avert', 'chins', 'gayer', 'atoms', 'chine', 'china',
'thwap', 'chino', 'coyer', 'chink', 'nulls', 'lingo', 'whoso', 'stern', 'spoke', 'cruft',
'untie', 'until', 'duals', 'relay', 'relax', 'yahoo', 'mires', 'tying', 'midst', 'copse',
'giros', 'famed', 'blade', 'fanin', 'cento', 'fames', 'pints', 'rayon', 'pinto', 'shiki',
'auger', 'clews', 'chase', 'hadst', 'typed', 'pimps', 'wrong', 'quipu', 'quips', 'chump',
'chums', 'types', 'eyers', 'buzzy', 'tetra', 'alias', 'keeps', 'aping', 'ovule', 'aargh',
'weals', 'waled', 'wales', 'unpeg', 'duvet', 'slate', 'drabs', 'beaus', 'twits', 'beaut',
'beaux', 'slats', 'thyme', 'debut', 'nixie', 'dumps', 'arrow', 'debug', 'dumpy', 'bowls',
'allay', 'borne', 'golem', 'touts', 'smirk', 'waive', 'zetas', 'mason', 'adapt', 'bates',
'eared', 'bated', 'coeds', 'miaow', 'selfs', 'vitro', 'tusks', 'youse', 'tango', 'dulse',
'tangy', 'craws', 'pubic', 'palsy', 'crawl', 'surer', 'biffs', 'recto', 'biffy', 'recta',
'gator', 'dozes', 'dozer', 'fasts', 'shyly', 'spiff', 'dozed', 'corny', 'cornu', 'picks',
'corns', 'dozen', 'hymen', 'divas', 'gripe', 'divan', 'doors', 'grips', 'henge', 'shall',
'shale', 'swiss', 'mouth', 'shalt', 'dummy', 'upend', 'grove', 'foist', 'pawer', 'liest',
'undue', 'runic', 'gauge', 'ulcer', 'caper', 'capes', 'lawzy', 'buxom', 'cupid', 'theme',
'bliss', 'caped', 'plate', 'lanai', 'plats', 'patch', 'fitly', 'cirri', 'niche', 'rings',
'score', 'scorn', 'cubby', 'claws', 'lamas', 'cards', 'miens', 'apish', 'tings', 'asker',
'askew', 'dents', 'login', 'argue', 'tinge', 'asked', 'tares', 'cills', 'matte', 'inode',
'tared', 'union', 'dicot', 'rooky', 'phyla', 'obese', 'joust', 'phlox', 'chile', 'child',
'chili', 'chill', 'manes', 'taper', 'delis', 'maned', 'betas', 'geoid', 'expat', 'veals',
'taped', 'spews', 'split', 'refix', 'goyim', 'refit', 'meads', 'bonny', 'bonne', 'veils',
'dyads', 'greys', 'beset', 'tilde', 'lasso', 'endue', 'coqui', 'match', 'brays', 'sulfa',
'quirk', 'quire', 'posed', 'lubes', 'birth', 'quirt', 'poser', 'poses', 'poset', 'bushy',
'bobby', 'malts', 'hooey', 'steps', 'creel', 'right', 'creek', 'crowd', 'creed', 'crown',
'crows', 'fagot', 'creep', 'gasps', 'hulky', 'hulks', 'sowed', 'witty', 'sower', 'lefts',
'lefty', 'veeps', 'annas', 'joule', 'emits', 'rebus', 'rebut', 'gauze', 'mocha', 'daffy',
'runts', 'mambo', 'runty', 'hallo', 'waits', 'serfs', 'raped', 'avail', 'width', 'rapes',
'music', 'halls', 'happy', 'offer', 'ligne', 'offed', 'beech', 'offen', 'otter', 'zilch',
'snugs', 'fermi', 'rerun', 'proud', 'minas', 'exist', 'smelt', 'mired', 'floor', 'actor',
'flood', 'warms', 'smell', 'lores', 'palms', 'teats', 'palmy', 'whets', 'melba', 'dirks',
'glass', 'obits', 'dotes', 'doter', 'chain', 'skate', 'doted', 'chair', 'pacts', 'cheat',
'watsa', 'macho', 'icing', 'ameba', 'spate', 'mourn', 'stays', 'spats', 'exact', 'moola',
'cooks', 'cooky', 'leave', 'loads', 'droid', 'rents', 'attic', 'ogler', 'ogles', 'rente',
'ogled', 'roans', 'badge', 'druid', 'yards', 'alone', 'along', 'dusts', 'dolts', 'dusty',
'troth', 'queue', 'tasks', 'abash', 'abase', 'angry', 'purls', 'papas', 'scops', 'papal',
'filmy', 'films', 'scope', 'tines', 'logos', 'piles', 'privy', 'fawny', 'fawns', 'frogs',
'locks', 'matzo', 'hides', 'echos', 'stole', 'hones', 'litre', 'silos', 'savor', 'dooms',
'ruder', 'lulab', 'cavil', 'remap', 'slush', 'ioctl', 'reman', 'mangy', 'mango', 'truck',
'mange', 'truce', 'haute', 'flips', 'years', 'yearn', 'deity', 'ovals', 'thumb', 'limby',
'muser', 'thump', 'limbo', 'mused', 'apron', 'deads', 'plunk', 'sepal', 'veiny', 'veins',
'edify', 'owing', 'troll', 'joker', 'brags', 'abide', 'curbs', 'siege', 'bumph', 'quite',
'bumps', 'bhoys', 'bumpy', 'quits', 'typal', 'gilts', 'dunno', 'bassi', 'marls', 'hames',
'hooch', 'vacua', 'vacuo', 'mucho', 'chide', 'croup', 'velds', 'veldt', 'wrath', 'draft',
'sayer', 'antis', 'shawl', 'shawm', 'emote', 'veers', 'antic', 'herds', 'abler', 'plein',
'rival', 'folly', 'coats', 'scuba', 'cowed', 'nicer', 'alley', 'chert', 'knead', 'aside',
'masse', 'paged', 'ruffs', 'pager', 'pages', 'byway', 'drive', 'sodas', 'batik', 'dolor',
'cobra', 'lotus', 'mince', 'merit', 'fecal', 'fibre', 'gourd', 'cloak', 'slues', 'tears',
'going', 'actin', 'teary', 'neato', 'neath', 'nonce', 'clank', 'clang', 'tuans', 'mondo',
'clans', 'bombe', 'prima', 'primo', 'mumbo', 'roger', 'primp', 'prims', 'where', 'nerve',
'chaws', 'raged', 'atilt', 'dived', 'dives', 'diver', 'rages', 'mecca', 'poops', 'sites',
'goers', 'teeny', 'wests', 'moldy', 'silts', 'moons', 'teens', 'silty', 'moony', 'molds',
'decks', 'gappy', 'umbel', 'farts', 'shahs', 'adept', 'punts', 'spare', 'spark', 'umber',
'quack', 'loafs', 'demur', 'coked', 'moans', 'cokes', 'kerbs', 'booms', 'teddy', 'casus',
'boomy', 'vials', 'bolas', 'buret', 'wants', 'lanes', 'wanta', 'breve', 'wilco', 'tomes',
'polly', 'girts', 'hayey', 'polls', 'hayer', 'dints', 'hayed', 'scats', 'necks', 'pinko',
'canoe', 'canon', 'pinky', 'pinks', 'spunk', 'yules', 'shuts', 'shute', 'aitch', 'liers',
'licit', 'wirer', 'wires', 'edged', 'coder', 'edger', 'edges', 'amuck', 'costa', 'hubba',
'exeat', 'costs', 'gorse', 'genie', 'hubby', 'being', 'slime', 'hades', 'slimy', 'slims',
'roves', 'rover', 'uncap', 'skied', 'dicky', 'dryly', 'doyen', 'roved', 'dicks', 'skies',
'skier', 'vagus', 'romps', 'snarl', 'snark', 'snarf', 'snare', 'vague', 'gimme', 'inter',
'junco', 'fives', 'fiver', 'pushy', 'magma', 'amino', 'lucid', 'refer', 'wolds', 'power',
'poise', 'flabs', 'yobbo', 'gyppy', 'stone', 'blabs', 'taxon', 'taxol', 'tumor', 'stony',
'shied', 'mopes', 'esses', 'image', 'moped', 'shies', 'pivot', 'braes', 'jerks', 'dishy',
'gleam', 'glean', 'meals', 'myths', 'evict', 'coifs', 'missy', 'saris', 'bunds', 'holey',
'tripe', 'flirt', 'dirty', 'torsi', 'torso', 'trips', 'dirts', 'laird', 'zebus', 'oweth',
'lairs', 'walks', 'creak', 'cream', 'bwana', 'tight', 'puppy', 'faxes', 'beaky', 'annex',
'slant', 'terra', 'gifts', 'herbs', 'proem', 'faxed', 'terry', 'narcs', 'herby', 'slang',
'scuds', 'thorn', 'acids', 'grook', 'mimic', 'scudi', 'scudo', 'coots', 'axles', 'retch',
'degas', 'neigh', 'tours', 'axled', 'oaths', 'riots', 'smile', 'mufti', 'eyrie', 'baton',
'diary', 'offal', 'cable', 'heist', 'large', 'pesky', 'dusky', 'harry', 'small', 'largo',
'dusks', 'viers', 'gulfs', 'grays', 'clock', 'fucks', 'gouty', 'gouts', 'nurse', 'houri',
'hours', 'shops', 'zooks', 'prior', 'plink', 'young', 'rusks', 'noons', 'pears', 'pearl',
'goeth', 'firth', 'blaze', 'rinds', 'nomad', 'aleph', 'abets', 'krill', 'lotsa', 'kaput',
'learn', 'grope', 'bidet', 'bides', 'bider', 'salty', 'sense', 'bided', 'dress', 'salts',
'burgs', 'viand', 'dilly', 'cling', 'dills', 'clink', 'waved', 'wiles', 'plant', 'lanky',
'plans', 'plane', 'waver', 'waves', 'plank', 'pigmy', 'rowdy', 'ortho', 'turps', 'patio',
'kaiak', 'bocce', 'peppy', 'bocci', 'trade', 'paper', 'rooty', 'signs', 'roots', 'saucy',
'zippy', 'laced', 'licks', 'duomo', 'deeds', 'lacer', 'laces', 'nifty', 'sauce', 'lacey',
'snobs', 'gipsy', 'weeds', 'idols', 'weedy', 'fount', 'found', 'execs', 'dosed', 'bends',
'blued', 'doser', 'doses', 'blues', 'bluer', 'silky', 'dicut', 'silks', 'bubba', 'downs',
'risen', 'proxy', 'acorn', 'riser', 'rises', 'amped', 'pairs', 'dimer', 'clump', 'shnor',
'major', 'gazed', 'celeb', 'gazer', 'gazes', 'luaus', 'guess', 'heads', 'guest', 'swipe',
'tangs', 'heady', 'saint', 'ilium', 'gnash', 'mural', 'grace', 'modes', 'vocab', 'frock',
'dikes', 'vocal', 'tummy', 'video', 'taxis', 'apers', 'mossy', 'blond', 'odors', 'bract',
'brack', 'frail', 'knobs', 'brace', 'mends', 'busby', 'saxes', 'nasal', 'tryst', 'virus',
'sumps', 'sarge', 'model', 'arson', 'covey', 'torus', 'cover', 'coves', 'coven', 'flits',
'affix', 'ichor', 'wraps', 'gooey', 'solum', 'nares', 'beamy', 'scuff', 'beams', 'emirs',
'sunny', 'hilts', 'peril', 'twill', 'enemy', 'sects', 'riven', 'tabby', 'bytes', 'rived',
'slabs', 'enema', 'rives', 'river', 'rivet', 'bulky', 'bulks', 'toons', 'nicad', 'knees',
'muted', 'movie', 'verbs', 'kneed', 'mynah', 'muter', 'mutes', 'buoys', 'verst', 'pagan',
'harps', 'harpy', 'scamp', 'scams', 'whole', 'patty', 'dipso', 'drunk', 'acted', 'jowls',
'jowly', 'devil', 'filth', 'imbed', 'longs', 'raced', 'racer', 'races', 'awake', 'towns',
'slobs', 'sixes', 'slyly', 'caged', 'cagey', 'error', 'robin', 'cages', 'cager', 'pound',
'swags', 'ducky', 'ducks', 'sitar', 'chasm', 'exult', 'funny', 'decor', 'doozy', 'kills',
'welts', 'maids', 'educe', 'ingot', 'snail', 'cigar', 'alert', 'leapt', 'leaps', 'rabid',
'nouns', 'mavis', 'stack', 'focal', 'picky', 'maker', 'bawls', 'feces', 'kelly', 'nappy',
'kerfs', 'salvo', 'glitz', 'salve', 'aroma', 'stunt', 'doily', 'thees', 'cuffs', 'aloha',
'hovel', 'eager', 'input', 'niece', 'wives', 'quest', 'towel', 'bruit', 'spine', 'spina',
'spiny', 'bogie', 'bruin', 'spins', 'canst', 'pings', 'sighs', 'sight', 'eclat', 'oddly',
'gruel', 'mummy', 'didot', 'didos', 'lubra', 'calyx', 'carob', 'wells', 'caron', 'tidal',
'carol', 'carom', 'fouls', 'agave', 'irked', 'locus', 'gases', 'lithe', 'litho', 'opens',
'pyxie', 'jacks', 'tally', 'slump', 'slums', 'fades', 'fader', 'faded', 'haunt', 'rehab',
'thugs', 'codes', 'rhumb', 'codex', 'coded', 'swirl', 'sails', 'scrub', 'hives', 'hiver',
'sided', 'scrum', 'dweeb', 'mealy', 'sides', 'hived', 'hells', 'wafer', 'holes', 'holer',
'harks', 'fresh', 'holed', 'hello', 'essay', 'toted', 'melts', 'gamba', 'totem', 'blebs',
'totes', 'toter', 'fusty', 'amiss', 'agues', 'glows', 'vetch', 'curds', 'glees', 'curdy',
'oakum', 'unzip', 'balls', 'llama', 'forks', 'magic', 'keens', 'marry', 'fewer', 'trite',
'crook', 'imply', 'croon', 'haiku', 'foals', 'index', 'twine', 'gooky', 'firma', 'twink',
'gooks', 'twins', 'lolls', 'firms', 'lolly', 'twiny', 'zincs', 'apace', 'punch', 'spake',
'feist', 'great', 'coops', 'umiak', 'derby', 'groks', 'makes', 'kerns', 'hasps', 'thats',
'altho', 'tools', 'getup', 'gelds', 'folky', 'doubt', 'humus', 'bonds', 'pygmy', 'drily',
'bally', 'mebbe', 'larch', 'drill', 'newts', 'wedge', 'reeds', 'reedy', 'nears', 'wedgy',
'flogs', 'teals', 'clogs', 'paled', 'wares', 'delay', 'mumps', 'opine', 'pales', 'obeys',
'nones', 'await', 'iambs', 'wrens', 'racks', 'pards', 'sprue', 'rills', 'robot', 'allot',
'allow', 'okapi', 'alloy', 'rille', 'thigh', 'volts', 'yawps', 'swain', 'comma', 'kivas',
'baron', 'moots', 'decay', 'decal', 'decaf', 'hobby', 'snaky', 'snake', 'abaft', 'truth',
'paler', 'tents', 'doing', 'joyed', 'books', 'banal', 'tenth', 'bolos', 'valve', 'venom',
'troop', 'yawny', 'yawns', 'tempi', 'tempo', 'temps', 'graze', 'tempt', 'scary', 'spill',
'scarp', 'could', 'scars', 'cunts', 'scare', 'scarf', 'spilt', 'piney', 'blown', 'pines',
'yells', 'scene', 'owned', 'blowy', 'hertz', 'khans', 'owner', 'blows', 'scent', 'yella',
'prank', 'vixen', 'lumen', 'ounce', 'haves', 'gummy', 'argot', 'vouch', 'elite', 'haven',
'steel', 'unmap', 'trike', 'steed', 'dower', 'psalm', 'agate', 'unman', 'steep', 'steer',
'false', 'heeds', 'babel', 'mills', 'babes', 'cozen', 'manor', 'medal', 'prove', 'ascot',
'noire', 'biked', 'briny', 'bring', 'biker', 'bikes', 'rouge', 'rough', 'brink', 'pause',
'meant', 'gnaws', 'lucks', 'lucky', 'autos', 'metes', 'wring', 'sorts', 'smash', 'hoses',
'neons', 'taxer', 'vying', 'stuff', 'hosed', 'taxed', 'exude', 'frame', 'meted', 'coils',
'posse', 'synod', 'email', 'oncet', 'butts', 'ovoid', 'keels', 'butte', 'hammy', 'yawed',
'wists', 'marts', 'webby', 'hauls', 'laity', 'labor', 'farad', 'oxlip', 'drank', 'waste',
'moved', 'laser', 'lases', 'coals', 'lased', 'ultra', 'ombre', 'groin', 'tenon', 'fugal',
'tenor', 'goths', 'defun', 'belch', 'pumas', 'logic', 'kopek', 'colts', 'audit', 'lupus',
'genus', 'olios', 'polyp', 'dinar', 'audio', 'reefs', 'gully', 'flesh', 'gulls', 'tansy',
'rooms', 'floes', 'roomy', 'stung', 'idiom', 'kirks', 'toyed', 'oinks', 'crack', 'toyer',
'oinky', 'wimpy', 'taunt', 'cedar', 'crisp', 'onion', 'sleds', 'resin', 'prier', 'bulgy',
'pried', 'dashy', 'nutsy', 'lowly', 'grids', 'thief', 'peaty', 'flush', 'peats', 'glyph',
'huzza', 'merge', 'avoid', 'rifer', 'shone', 'uvula', 'kiddo', 'stagy', 'manta', 'stags',
'maven', 'picot', 'belay', 'talus', 'loans', 'stage', 'kelps', 'kelpy', 'miner', 'seeds',
'seedy', 'cadet', 'pussy', 'booed', 'roads', 'afoot', 'twain', 'spots', 'kooky', 'yawls',
'kooks', 'baulk', 'okays', 'yarns', 'pixie', 'pithy', 'grate', 'grata', 'count', 'garbs',
'ruses', 'cored', 'booky', 'didst', 'lauds', 'tides', 'oring', 'vined', 'tided', 'laude',
'ghost', 'hoots', 'agars', 'amahs', 'rural', 'trims', 'abhor', 'saver', 'saves', 'yikes',
'huffy', 'huffs', 'saved', 'ebbed', 'votes', 'voter', 'worts', 'voted', 'regal', 'whack',
'gimel', 'anent', 'manic', 'mania', 'noels', 'whisk', 'whish', 'pinch', 'nobby', 'poppy',
'whist', 'galas', 'tunas', 'panda', 'petri', 'above', 'mosts', 'godly', 'sinks', 'jolts',
'algin', 'tufas', 'studs', 'kudos', 'items', 'smoky', 'envoy', 'adopt', 'smoke', 'envoi',
'spawn', 'pitas', 'total', 'saran', 'coins', 'knoll', 'lorry', 'darns', 'bilge', 'award',
'aware', 'bilgy', 'soils', 'tecum', 'oxide', 'elbow', 'piers', 'micks', 'flunk', 'indie',
'cited', 'flung', 'woman', 'cites', 'fudgy', 'gaped', 'farce', 'agony', 'gaper', 'agone',
'boats', 'beach', 'zingy', 'bebop', 'fever', 'bares', 'barer', 'after', 'bared', 'suing',
'scull', 'padre', 'hasty', 'egged', 'grogs', 'greet', 'greek', 'green', 'worst', 'davit',
'order', 'greed', 'egger', 'salon', 'toddy', 'byres', 'tiffs', 'japan', 'mayor', 'bibbs',
'hodad', 'sheaf', 'valor', 'vents', 'shear', 'woken', 'liras', 'break', 'bream', 'bread',
'aport', 'anion', 'crock', 'dingo', 'doles', 'rocks', 'axing', 'dings', 'crocs', 'doled',
'voxel', 'prawn', 'flock', 'forts', 'forty', 'forte', 'pined', 'clads', 'hogan', 'putty',
'putts', 'sprit', 'prigs', 'louse', 'lousy', 'renew', 'sprig', 'grift', 'laxly', 'comic',
'rated', 'rates', 'rater', 'snags', 'tithe', 'picas', 'mercy', 'guild', 'guile', 'binds',
'guilt', 'minus', 'banes', 'dildo', 'cadge', 'etext', 'realm', 'laden', 'laded', 'swims',
'gravy', 'lucre', 'ouzel', 'hawed', 'phase', 'fatly', 'grave', 'ducal', 'swami', 'argon',
'swamp', 'ducat', 'fussy', 'dames', 'doped', 'bimbo', 'brief', 'dopey', 'wrung', 'dopes',
'doper', 'toast', 'eider', 'gutsy', 'unjam', 'vends', 'cocci', 'agape', 'ardor', 'yolky',
'gored', 'apian', 'nasty', 'slack', 'trios', 'winos', 'morph', 'unmet', 'stead', 'gears',
'steak', 'steal', 'steam', 'ghoul', 'draws', 'obeah', 'caved', 'props', 'drawn', 'caves',
'slugs', 'clued', 'loose', 'terms', 'scuse', 'diest', 'clues', 'oomph', 'frump', 'hempy',
'amble', 'hemps', 'rawly', 'gable', 'tough', 'spear', 'codon', 'wider', 'heals', 'speak',
'petty', 'leech', 'hoist', 'rasps', 'ajuga', 'harms', 'waked', 'raspy', 'voice', 'souse',
'sting', 'dizzy', 'brake', 'exile', 'stint', 'whiny', 'syncs', 'synch', 'bunny', 'wheel',
'biles', 'wheee', 'swell', 'alums', 'wispy', 'campo', 'wisps', 'mammy', 'taint', 'campy',
'mamma', 'camps', 'gesso', 'photo', 'adzes', 'wasps', 'waspy', 'extol', 'biome', 'antes',
'hills', 'yores', 'fared', 'hilly', 'exalt', 'shout', 'anted', 'fares', 'cukes', 'afire',
'boxed', 'boxes', 'boxer', 'barge', 'unwon', 'axels', 'night', 'augur', 'mazer', 'mazes',
'dyers', 'taffy', 'sends', 'nisei', 'tapir', 'hypos', 'mazed', 'ghoti', 'humor', 'mulls',
'dolce', 'dribs', 'cabby', 'flaws', 'chafe', 'chaff', 'dines', 'diner', 'coral', 'anima',
'dined', 'dotty', 'eight', 'hocks', 'croak', 'lavas', 'float', 'bound', 'clomp', 'crags',
'nodal', 'frill', 'fight', 'jinns', 'tints', 'snowy', 'snows', 'ceded', 'ceder', 'cedes',
'reset', 'coset', 'dowry', 'liens', 'sprog', 'mails', 'aorta', 'dacha', 'poufs', 'moors',
'ephah', 'cacao', 'dimly', 'dying', 'stake', 'shoji', 'orate', 'omega', 'pacer', 'paces',
'ketch', 'loyal', 'paced', 'igloo', 'dance', 'datum', 'flyby', 'grape', 'flask', 'graph',
'flash', 'middy', 'grapy', 'brown', 'blash', 'vegan', 'huger', 'blast', 'brows', 'turns',
'redly', 'brine', 'woven', 'upper', 'brave', 'brava', 'bravo', 'yolks', 'grump', 'upped',
'pryer', 'cocas', 'cargo', 'curse', 'havoc', 'chuff', 'peels', 'genes', 'genet', 'gorge',
'sieve', 'hoops', 'fogey', 'ukase', 'reals', 'trial', 'bangs', 'triad', 'hamza', 'atria',
'extra', 'sebum', 'softy', 'softs', 'knurl', 'drays', 'slued', 'cuter', 'slays', 'cluck',
'finis', 'ninny', 'futon', 'terce', 'qophs', 'felts', 'finif', 'tabus', 'purge', 'trans',
'heart', 'styes', 'hears', 'saith', 'gales', 'topic', 'heard', 'abort', 'gabby', 'tzars',
'occur', 'writs', 'means', 'prexy', 'write', 'flank', 'meany', 'vases', 'crepe', 'noses',
'nosey', 'nosed', 'crept', 'stilt', 'ender', 'tubas', 'brain', 'stile', 'tubal', 'braid',
'mixup', 'birds', 'ethic', 'forma', 'sinus', 'curly', 'warps', 'curls', 'hewed', 'forms',
'hewer', 'tiara', 'feats', 'fling', 'bilks', 'flint', 'recap', 'perdu', 'jaggy', 'deify',
'cuspy', 'cusps', 'fired', 'cairn', 'goosy', 'goose', 'fires', 'firer', 'taxes', 'hymns',
'pills', 'album', 'shown', 'space', 'irony', 'showy', 'shays', 'shows', 'punky', 'thong',
'gaffs', 'quark', 'quart', 'rebel', 'gaffe', 'alkyd', 'alkyl', 'domes', 'seest', 'domed',
'blind', 'mayst', 'tippy', 'blini', 'blink', 'yurts', 'drove', 'sheep', 'sheer', 'sheet',
'tusky', 'waned', 'breed', 'dawns', 'psoas', 'wilts', 'sheen', 'wanes', 'kepis', 'larks',
'sorer', 'sores', 'cults', 'baldy', 'arity', 'raper', 'balds', 'kabob', 'dinky', 'dinks',
'lurid', 'rooks', 'angel', 'saute', 'boule', 'anger', 'lumpy', 'lumps', 'inked', 'snout',
'inker', 'begin', 'prick', 'price', 'shorn', 'renal', 'tooth', 'toots', 'erred', 'mecum',
'mains', 'fifty', 'femur', 'yukky', 'fifth', 'snack', 'ratio', 'stair', 'title', 'skits',
'klugy', 'staid', 'kluge', 'stain', 'truly', 'loath', 'moxie', 'bigly', 'keyed', 'baits',
'sonar', 'keyer', 'aerie', 'reels', 'burst', 'spore', 'unfit', 'afoul', 'sport', 'unfix',
'togas', 'feuds', 'glaze', 'garde', 'pesos', 'pluck', 'blame', 'hurts', 'broil', 'duces',
'cycad', 'pawls', 'comet', 'comes', 'comer', 'heron', 'sulky', 'jeans', 'sulks', 'looms',
'amine', 'brats', 'caret', 'carer', 'cares', 'cared', 'jerky', 'krona', 'avian', 'krone',
'fours', 'stems', 'foggy', 'crumb', 'thunk', 'these', 'winks', 'trick', 'crump', 'biped',
'dregs', 'trice', 'mucus', 'heels', 'worry', 'media', 'medic', 'aphid', 'epoch', 'finks',
'aphis', 'noble', 'fruit', 'plops', 'nobly', 'purer', 'traps', 'puree', 'duple', 'heaps',
'edema', 'topos', 'topoi', 'touch', 'speed', 'death', 'pocks', 'pocky', 'verse', 'versa',
'verso', 'seams', 'hover', 'frown', 'stunk', 'larva', 'rules', 'ruler', 'seamy', 'gonna',
'vises', 'early', 'vised', 'using', 'earls', 'fryer', 'stuns', 'ruled', 'gismo', 'faire',
'hacks', 'nurbs', 'viral', 'quids', 'forky', 'ethos', 'wheat', 'epsom', 'throb', 'sixth',
'chefs', 'seine', 'throe', 'sixty', 'wheal', 'throw', 'piety', 'crink', 'pieta', 'bitty',
'stare', 'shags', 'hunks', 'hunky', 'socle', 'stark', 'start', 'stars', 'piton', 'bebug',
'leach', 'groan', 'kiths', 'lymph', 'groat', 'toned', 'fraud', 'tones', 'toner', 'skews',
'tutus', 'fugit', 'sales', 'mover', 'moves', 'valid', 'fools', 'polar', 'treks', 'nudie',
'drift', 'vines', 'deary', 'repay', 'corer', 'cores', 'redux', 'monte', 'month', 'pique',
'messy', 'corps', 'icons', 'nodes', 'robes', 'parry', 'rogue', 'robed', 'begot', 'resay',
'louis', 'resaw', 'lulls', 'fence', 'gyves', 'gayly', 'gyved', 'lurch', 'quoit', 'quoin',
'trunk', 'arena', 'ureas', 'ahead', 'laved', 'whine', 'popes', 'drubs', 'laves', 'laver',
'zowie', 'aimer', 'limos', 'aimed', 'taker', 'takes', 'ephod', 'girds', 'taken', 'turbo',
'erode', 'tarns', 'broke', 'hurry', 'grill', 'wafts', 'pawns', 'peals', 'smurf', 'swash',
'situs', 'nippy', 'zappy', 'lacks', 'calms', 'chops', 'menus', 'tried', 'sneak', 'tries',
'trier', 'drear', 'dread', 'banks', 'dream', 'urine', 'pends', 'fined', 'miter', 'mites',
'heros', 'cutie', 'fines', 'finer', 'diems', 'vomit', 'greps', 'ninja', 'fulls', 'payer',
'fully', 'payed', 'payee', 'blest', 'fairy', 'heavy', 'lippy', 'warty', 'hales', 'haler',
'blank', 'wacky', 'haled', 'wacko', 'evens', 'heave', 'event', 'dears', 'ftped', 'since',
'jolly', 'wordy', 'issue', 'smock', 'drink', 'earns', 'inert', 'algal', 'maths', 'algae',
'lemur', 'daisy', 'jutes', 'blush', 'knots', 'quiff', 'ville', 'elder', 'hying', 'hangs',
'craps', 'warts', 'maple', 'beret', 'horse', 'inure', 'bunts', 'swive', 'horsy', 'bowed',
'slosh', 'bowel', 'basal', 'bower', 'norms', 'tunic', 'mussy', 'dhows', 'bride', 'drake',
'mooed', 'harts', 'macaw', 'novas', 'juicy', 'juice', 'novae', 'koala', 'rebid', 'henna',
'umbra', 'barmy', 'barms', 'aired', 'hires', 'hirer', 'quote', 'eater', 'quota', 'hired',
'airer', 'eaten', 'alpha', 'roids', 'clear', 'tubed', 'cleat', 'tongs', 'dynes', 'clean',
'fossa', 'unwed', 'skein', 'tubes', 'tuber', 'hypes', 'hyper', 'humid', 'boozy', 'sheik',
'booze', 'hyped', 'randy', 'abend', 'rands', 'trees', 'strut', 'feels', 'bedew', 'strum',
'boils', 'treed', 'piing', 'adlib', 'fluff', 'boost', 'ohmic', 'corgi', 'withs', 'ixnay',
'crams', 'cramp', 'toyon', 'kilos', 'close', 'gouda', 'tolls', 'durst', 'spray', 'gongs',
'pshaw', 'genre', 'topes', 'dally', 'sprat', 'gaunt', 'jawed', 'vault', 'liked', 'liken',
'skips', 'liker', 'likes', 'stamp', 'empty', 'lived', 'packs', 'liven', 'wimps', 'deter',
'bight', 'lives', 'liver', 'while', 'ought', 'fleet', 'guide', 'flees', 'petal', 'unfed',
'reads', 'ready', 'grant', 'flays', 'madly', 'grand', 'octal', 'fatty', 'optic', 'bonus',
'tufty', 'bromo', 'plugs', 'tufts', 'comas', 'older', 'grind', 'grins', 'olden', 'chore',
'staph', 'cocky', 'cocks', 'botch', 'carat', 'elves', 'wised', 'march', 'stein', 'wises',
'wiser', 'wings', 'ponds', 'thews', 'moire', 'vests', 'bulge', 'dreck', 'donna', 'wrack',
'cones', 'wombs', 'mauve', 'lathe', 'coney', 'coned', 'pries', 'quoth', 'laths', 'lobar',
'slash', 'plebs', 'tabor', 'laker', 'lakes', 'infra', 'jazzy', 'plebe', 'lasts', 'plots',
'taboo', 'ochre', 'shine', 'splay', 'letup', 'blocs', 'hinge', 'shins', 'shiny', 'papaw',
'block', 'ensue', 'rolls', 'visas', 'douse', 'harem', 'bossa', 'newel', 'inept', 'etude',
'newer', 'frosh', 'hares', 'bossy', 'skulk', 'skull', 'doest', 'gecko', 'vires', 'fears',
'beryl', 'forgo', 'forge', 'vireo', 'duddy', 'swede', 'cribs', 'blend', 'orbit', 'fosse',
'depth', 'heats', 'bribe', 'washy', 'mores', 'flaks', 'farms', 'morel', 'icier', 'stave',
'suits', 'shack', 'suite', 'dogie', 'kitty', 'tenet', 'snide', 'tonal', 'exits', 'stiff',
'frays', 'shish', 'brims', 'booty', 'blitz', 'boots', 'muffs', 'booth', 'click', 'poled',
'plays', 'vales', 'valet', 'poles', 'poler', 'playa', 'quell', 'niter', 'chant', 'repel',
'koine', 'micas', 'claim', 'clout', 'meson', 'cloud', 'imbue', 'snoot', 'snoop', 'hydra',
'snood', 'noisy', 'snook', 'hydro', 'salad', 'tench', 'lapse', 'lazed', 'donut', 'lazes',
'drops', 'wryer', 'vaunt', 'wharf', 'iodic', 'links', 'hider', 'atone', 'flake', 'skirt',
'egret', 'jails', 'hafts', 'titre', 'hafta', 'jiffy', 'selah', 'jiffs', 'piggy', 'gauzy',
'gulps', 'catty', 'scoop', 'prays', 'scoot', 'bairn', 'soggy', 'sperm', 'refry', 'demon',
'swigs', 'brood', 'outer', 'broom', 'brook', 'outen', 'pixel', 'turfs', 'frond', 'turfy',
'stoup', 'hexes', 'stout', 'hands', 'front', 'handy', 'naiad', 'guard', 'slide', 'gists',
'pools', 'leash', 'globe', 'snaps', 'sands', 'globs', 'sandy', 'butch', 'calix', 'armor',
'demos', 'memes', 'cause', 'jives', 'stews', 'wines', 'bipod', 'acked', 'wined', 'jived',
'sneer', 'mares', 'tulle', 'shrew', 'route', 'timer', 'times', 'shred', 'timed', 'routs',
'bitch', 'conga', 'fella', 'paves', 'paver', 'fells', 'ankle', 'culls', 'prong', 'cowls',
'pssst', 'wazoo', 'lists', 'feint', 'secco', 'fuzzy', 'spurn', 'aught', 'bloat', 'cuing',
'shill', 'spurt', 'spurs', 'beefs', 'kayos', 'preps', 'sings', 'kebob', 'jaunt', 'singe',
'visor', 'snubs', 'fuels', 'adieu', 'duels', 'bosun', 'weans', 'moths', 'rigor', 'mothy',
'eject', 'upset', 'skunk', 'noway', 'crate', 'poesy', 'passe', 'based', 'fores', 'varia',
'wreak', 'baser', 'libra', 'surfs', 'dodge', 'podia', 'slows', 'jammy', 'boric', 'joint',
'joins', 'buyer', 'sassy', 'dodgy', 'tuned', 'topaz', 'golfs', 'tunes', 'tuner', 'widow',
'shake', 'klutz', 'rifts', 'stats', 'state', 'limbs', 'merry', 'melds', 'sniff', 'trove',
'minds', 'muses', 'admit', 'knops', 'nymph', 'admix', 'hussy', 'kings', 'aloes', 'tread',
'wills', 'polka', 'aspic', 'treap', 'treat', 'heigh', 'vinca', 'kicky', 'corks', 'nates',
'corky', 'novel', 'ripen', 'chalk', 'riper', 'maces', 'macer', 'flubs', 'taupe', 'claps',
'bucks', 'lambs', 'fondu', 'odder', 'began', 'begat', 'parts', 'party', 'joist', 'spree',
'lieth', 'luvya', 'lunch', 'drone', 'skill', 'milch', 'femme', 'talcs', 'titty', 'lures',
'lurer', 'knish', 'lured', 'mitre', 'sonic', 'wooed', 'ledge', 'ample', 'livid', 'okras',
'amply', 'fleas', 'ikats', 'sizer', 'sizes', 'sages', 'sager', 'sized', 'sissy', 'lends',
'lager', 'pewit', 'glare', 'refly', 'leers', 'glary', 'peter', 'leery', 'broad', 'octet',
'outgo', 'nabob', 'wends', 'fanny', 'turdy', 'hurly', 'turds', 'hurls', 'pulpy', 'stows',
'pulps', 'sways', 'miffs', 'rodeo', 'beige', 'cocos', 'cocoa', 'calks', 'tsars', 'glens',
'weepy', 'weeps', 'inner', 'hoofs', 'north', 'xerox', 'astro', 'marge', 'wince', 'winch',
'mylar', 'paean', 'leper', 'hiked', 'cells', 'rumba', 'pansy', 'cruel', 'limit', 'cello',
'piece', 'lobed', 'penny', 'twist', 'slaws', 'lobes', 'piker', 'pikes', 'folio', 'ruble',
'folia', 'folic', 'finch', 'giddy', 'dewed', 'smogs', 'pinup', 'dewey', 'shuns', 'shunt',
'inset', 'aided', 'knelt', 'elegy', 'aider', 'aides', 'whose', 'gamut', 'buddy', 'sines',
'sinew', 'dukes', 'sorry', 'fists', 'fisty', 'arums', 'weald', 'smack', 'sleek', 'crops',
'velar', 'shlep', 'himbo', 'force', 'quilt', 'fixit', 'warns', 'crave', 'quill', 'gawky',
'surds', 'wreck', 'gawks', 'fjord', 'basks', 'mamas', 'orbed', 'never', 'aquas', 'porno',
'nanny', 'boron', 'aquae', 'oozes', 'tapes', 'sedum', 'rests', 'golds', 'hokey', 'oozed',
'mashy', 'moray', 'hunch', 'jujus', 'elude', 'immix', 'spays', 'moral', 'poems', 'welch',
'mooch', 'barky', 'rebox', 'ratty', 'barks', 'pudgy', 'leaks', 'leaky', 'coons', 'lungs',
'quals', 'lunge', 'dogma', 'pecan', 'adult', 'qualm', 'loons', 'tweed', 'flora', 'kraut',
'trots', 'azoic', 'setup', 'worth', 'basso', 'guise', 'endow', 'defer', 'vodka', 'blips',
'fichu', 'honed', 'honey', 'foods', 'fiche', 'honer', 'aging', 'polio', 'strop', 'colds',
'polis', 'becks', 'corms', 'natch', 'plies', 'third', 'fungo', 'fungi', 'plied', 'fetus',
'toads', 'diddy', 'clave', 'fable', 'toady', 'carve', 'weeks', 'gents', 'downy', 'vivre',
'daubs', 'runny', 'ester', 'jilts', 'itchy', 'droll', 'lofts', 'roast', 'thens', 'lofty',
'loess', 'adobe', 'skint', 'tatty', 'skins', 'gunny', 'sluts', 'tales', 'nerts', 'lurks',
'debit', 'kiwis', 'whiff', 'abate', 'infix', 'aisle', 'humps', 'fetal', 'shush', 'deems',
'fleck', 'doffs', 'cloys', 'grade', 'ceils', 'unlit', 'ditch', 'grads', 'speck', 'dwelt',
'girly', 'hawks', 'girls', 'sidle', 'zeros', 'dwell', 'rasae', 'stoic', 'poohs', 'silly',
'sills', 'gaudy', 'telly', 'churl', 'churn', 'tells', 'horde', 'alibi', 'busks', 'specs',
'chest', 'chess', 'hoods', 'anole', 'savvy', 'maria', 'aways', 'alarm', 'dovey', 'doves',
'pavan', 'pruta', 'probe', 'ankhs', 'chord', 'owlet', 'hoary', 'debts', 'hoars', 'sugar',
'lisps', 'folks', 'hoard', 'edict', 'tiles', 'tiler', 'coast', 'tiled', 'zesty', 'braze',
'disco', 'discs', 'seeks', 'cower', 'dowel', 'coati', 'zoned', 'zones', 'snuff', 'paten',
'coxes', 'sorta', 'scrap', 'yanks', 'coxed', 'scram', 'pampa', 'credo', 'wears', 'weary',
'motto', 'egads', 'arced', 'mucky', 'conch', 'mucks', 'monad', 'quint', 'foray', 'ether',
'recut', 'riled', 'whews', 'recur', 'basis', 'three', 'erect', 'slyer', 'riles', 'frisk',
'basic', 'basil', 'basin', 'threw', 'roily', 'roils', 'halma', 'toper', 'abuts', 'toped',
'study', 'mousy', 'seven', 'shams', 'sushi', 'faker', 'fakes', 'shame', 'faked', 'amour',
'mouse', 'sever', 'grown', 'growl', 'belli', 'cools', 'belle', 'belly', 'grows', 'bells',
'lunes', 'meets', 'livre', 'overt', 'overs', 'yourn', 'flops', 'yours', 'facto', 'kinky',
'plash', 'plasm', 'kinks', 'psych', 'human', 'facts', 'skyed', 'polos', 'nudge', 'agile',
'royal', 'julep', 'slurp', 'ousel', 'reuse', 'ducts', 'natal', 'gofer', 'fifes', 'revet',
'maxim', 'revel', 'maxis', 'dense', 'carts', 'sifts', 'beget', 'carte', 'faery', 'astir',
'super', 'supes', 'tyres', 'lapis', 'haply', 'cadre', 'lapin', 'azure', 'boors', 'emcee',
'unsay', 'hotly', 'gloss', 'whats', 'fumed', 'chimp', 'fumer', 'fumes', 'slurs', 'chime',
'latus', 'nervy', 'redox', 'raids', 'sagas', 'daddy', 'damps', 'glans', 'petit', 'gland',
'wrier', 'addle', 'graft', 'vista', 'aunts', 'excel', 'holly', 'tardy', 'sling', 'slink',
'reign', 'russe', 'stoke', 'daily', 'teeth', 'souls', 'soppy', 'glebe', 'yummy', 'swoon',
'achoo', 'amaze', 'swoop', 'marks', 'yeast', 'tacos', 'sappy', 'lynch', 'pious', 'limes',
'limey', 'wurst', 'limed', 'limen', 'round', 'shave', 'jumpy', 'villa', 'sawed', 'villi',
'estop', 'slake', 'sunup', 'sawer', 'unbar', 'heres', 'herem', 'bauds', 'unban', 'dwarf',
'bloke', 'clerk', 'shift', 'odour', 'tromp', 'nylon', 'plume', 'sputa', 'elect', 'kebab',
'kayak', 'gluon', 'modus', 'verge', 'gonzo', 'visit', 'pelts', 'bazar', 'balks', 'balky',
'bosky', 'owest', 'rigid', 'olive', 'gnome', 'gassy', 'impel', 'repro', 'drags', 'bites',
'biter', 'lords', 'crazy', 'palls', 'lordy', 'agent', 'pally', 'craze', 'arbor', 'parch',
'sword', 'swore', 'sworn', 'mocks', 'waist', 'maybe', 'avant', 'oaten', 'abuzz', 'halos',
'kulak', 'serge', 'shoer', 'shoes', 'rabbi', 'shaky', 'shoed', 'lyric', 'pitch', 'equip',
'shako', 'grout', 'group', 'thank', 'thane', 'satyr', 'thanx', 'zings', 'texas', 'gapes',
'prime', 'tonic', 'views', 'axons', 'moron', 'zayin', 'fudge', 'pizza', 'vogue', 'brews',
'shews', 'lycra', 'aloof', 'pucks', 'homme', 'fazed', 'rebar', 'leeks', 'fazes', 'dutch',
'nudes', 'nuder', 'bayed', 'hefts', 'bombs', 'hefty', 'gouge', 'spier', 'spies', 'spiel',
'aioli', 'zombi', 'vinyl', 'spied', 'cough', 'watts', 'jakes', 'grist', 'thins', 'goest',
'thing', 'funky', 'thine', 'funks', 'oxbow', 'think', 'first', 'carry', 'murks', 'murky',
'slept', 'tuxes', 'fiery', 'daunt', 'paved', 'ivied', 'pukka', 'gotta', 'mitts', 'squaw',
'clung', 'squat', 'wetly', 'clunk', 'squad', 'squab', 'haste', 'canna', 'frost', 'trace',
'track', 'baize', 'whizz', 'purty', 'tract', 'canny', 'absit', 'vapor', 'damns', 'fills',
'angst', 'scows', 'filly', 'scowl', 'sigma', 'fishy', 'delta', 'flack', 'label', 'bonks',
'plumb', 'black', 'helix', 'plumy', 'germs', 'plums', 'plump', 'hippo', 'sable', 'bevel',
'stomp', 'slily', 'hippy', 'stoma', 'lochs', 'sited', 'yield', 'miler', 'miles', 'ruddy',
'peony', 'elide', 'peons', 'spars', 'klieg', 'chewy', 'chews', 'loped', 'tacit', 'lopes',
'loper', 'magna', 'dates', 'dater', 'rugby', 'icily', 'dated', 'tilth', 'profs', 'spang',
'terse', 'cutup', 'spank', 'rheum', 'slain', 'spans', 'zooey', 'tramp', 'trams', 'gronk',
'lisle', 'cawed', 'those', 'sound', 'kappa', 'punks', 'bathe', 'baths', 'zonal', 'ferny',
'harsh', 'belie', 'heirs', 'rimer', 'roost', 'munch', 'hullo', 'hulls', 'rimed', 'weave',
'layup', 'drain', 'macro', 'tagua', 'evils', 'epact', 'gates', 'gangs', 'among', 'money',
'wifey', 'gated', 'ethyl', 'bowie', 'paras', 'borax', 'ahhhh', 'hoers', 'docks', 'dodos',
'rocky', 'decoy', 'titan', 'toffy', 'erase', 'spasm', 'dingy', 'lotta', 'lotto', 'doggo',
'lunar', 'doggy', 'knife', 'ovens', 'skeet', 'awing', 'gules', 'drums', 'feeds', 'opium',
'hicks', 'smear', 'mixer', 'mixes', 'adman', 'knave', 'mixed', 'honky', 'lands', 'honks',
'strip', 'nohow', 'midis', 'bedim', 'fated', 'treys', 'anise', 'brute', 'ikons', 'fates',
'lions', 'chats', 'spicy', 'spics', 'buggy', 'duchy', 'spice', 'cacti', 'umped', 'ember',
'agora', 'pekoe', 'embed', 'moles', 'gumbo', 'carpy', 'hound', 'carps', 'again', 'twerp',
'field', 'prism', 'prise', 'lapel', 'gaols', 'aster', 'pukes', 'baddy', 'puked', 'legal',
'boons', 'sewed', 'casts', 'defog', 'roams', 'unsex', 'sewer', 'oases', 'husky', 'ovary',
'sicko', 'unsew', 'unset', 'caste', 'wormy', 'geode', 'worms', 'slung', 'talks', 'slunk',
'nines', 'ocher', 'puffs', 'puffy', 'scout', 'scour', 'purrs', 'forth', 'grubs', 'unrig',
'grabs', 'gnarl', 'phage', 'gonad', 'cilia', 'stood', 'opted', 'stool', 'stoop', 'plush',
'twang', 'oldie', 'hadda', 'dictu', 'bible', 'sofas', 'dicta', 'milky', 'girth', 'milks',
'buses', 'bused', 'xored', 'memos', 'wiped', 'tacks', 'libel', 'tacky', 'dunks', 'wiper',
'wipes', 'pismo', 'deism', 'purse', 'brisk', 'goads', 'sylph', 'deist', 'aglow', 'dazes',
'sucks', 'halts', 'dazed', 'reaps', 'wails', 'shark', 'morts', 'prods', 'share', 'shard',
'doxie', 'hilum', 'kefir', 'sharp', 'iotas', 'siren', 'sired', 'siree', 'thous', 'plena',
'thaws', 'ulnas', 'ulnar', 'sires', 'bleat', 'blear', 'blood', 'bloom', 'bleak', 'chute',
'yipes', 'brads', 'scrod', 'radar', 'dough', 'pests', 'adios', 'bosom', 'boson', 'emend',
'dolly', 'pesto', 'arias', 'dolls', 'chirp', 'orcas', 'males', 'walls', 'hails', 'ashen',
'toker', 'tokes', 'micro', 'token', 'goofy', 'toked', 'goofs', 'ports', 'clamp', 'clams',
'jings', 'house', 'monks', 'foxes', 'surly', 'jingo', 'foxed', 'ganef', 'thick', 'prink',
'rimes', 'print', 'ribby', 'bully', 'louts', 'bulls', 'golly', 'wired', 'omits', 'wadis',
'stabs', 'lyres', 'waged', 'shoat', 'shoal', 'wages', 'wager', 'razor', 'sates', 'jetty',
'least', 'paint', 'sated', 'pains', 'doges', 'lease', 'odium', 'dippy', 'stirs', 'youth',
'kapok', 'clods', 'idled', 'outta', 'idles', 'idler', 'paths', 'rower', 'built', 'couch',
'onset', 'rowed', 'lifts', 'build', 'solve', 'genii', 'chary', 'ileus', 'chars', 'flute',
'chart', 'comps', 'charm', 'ileum', 'chard', 'teems', 'sibyl', 'weigh', 'pease', 'orlon',
'gutty', 'carny', 'carne', 'chock', 'gutta', 'ambit', 'poach', 'fiend', 'gills', 'cysts',
'wonks', 'wonky', 'pions', 'tiros', 'judos', 'tyros', 'kikes', 'ovate', 'poxes', 'manly',
'luxes', 'sahib', 'chose', 'debar', 'rosin', 'rawer', 'prams', 'cuber', 'cubes', 'spumy',
'cubed', 'suede', 'bongo', 'point', 'gypsy', 'caked', 'gnats', 'bongs', 'helms', 'mikes',
'raise', 'fenny', 'stoae', 'miked', 'stoat', 'excon', 'stoas', 'slips', 'nukes', 'nuked',
'lings', 'unify', 'solid', 'skiff', 'dryad', 'coyly', 'vroom', 'cents', 'anode', 'axmen',
'aches', 'eland', 'torts', 'baste', 'elans', 'ached', 'tacet', 'torte', 'desks', 'timid',
'swish', 'rearm', 'halve', 'spent', 'flags', 'rears', 'entry', 'spend', 'nards', 'guano',
'shape', 'world', 'kited', 'hated', 'kites', 'opals', 'hates', 'hater', 'lades', 'knock',
'yucky', 'disks', 'glove', 'tibia', 'scrip', 'often', 'jibes', 'jiber', 'jibed', 'yogas',
'brent', 'scrim', 'scald', 'scale', 'balms', 'lardy', 'whomp', 'balmy', 'lards', 'bogus',
'scalp', 'scaly', 'crony', 'munge', 'mungy', 'nitty', 'mungs', 'crone', 'candy', 'drams',
'goods', 'juste', 'beano', 'goody', 'conks', 'drama', 'piled', 'slams', 'beans', 'jimmy',
'aleck', 'clack', 'liege', 'pares', 'parer', 'bores', 'borer', 'pared', 'paren', 'bored',
'gauss', 'hoped', 'serif', 'hopes', 'hoper', 'vivas', 'clips', 'jumbo', 'geese', 'omens',
'titer', 'crypt', 'pecks', 'pails', 'ogres', 'quaff', 'gross', 'admen', 'gulag', 'cater',
'monic', 'wards', 'bergs', 'delft', 'rinse', 'rants', 'tombs', 'query', 'strep', 'strew',
'shyer', 'suave', 'mower', 'chaps', 'helps', 'fovea', 'atlas', 'mowed', 'fatal', 'assay',
'rhyme', 'assai', 'legos', 'molar', 'molas', 'shock', 'codas', 'molal', 'dimes', 'tinny',
'chomp', 'nests', 'wahoo', 'dowdy', 'spuds', 'pipes', 'piper', 'pipet', 'rotor', 'fiord',
'piped', 'nacho', 'safer', 'safes', 'coped', 'bolls', 'climb', 'honor', 'coper', 'copes',
'named', 'manna', 'talon', 'namer', 'names', 'hoagy', 'faddy', 'beths', 'jests', 'peens',
'trait', 'dupes', 'duper', 'kiosk', 'fuzes', 'ahoys', 'trail', 'train', 'napes', 'fuzed',
'duped', 'hints', 'tease', 'mesas', 'gruff', 'fetch', 'unate', 'reran', 'boned', 'bones',
'boner', 'gores', 'holds', 'goner', 'stock', 'ruche', 'highs', 'bluff', 'fiats', 'drape',
'solon', 'lines', 'liner', 'linen', 'chief', 'solos', 'lined', 'imago', 'ricer', 'rices',
'wilds', 'meter', 'briar', 'horns', 'bunco', 'riced', 'horny', 'bunch', 'dungy', 'dungs',
'acres', 'marsh', 'azine', 'weber', 'pangs', 'spell', 'spelt', 'panga', 'flail', 'cider',
'ruing', 'pewee', 'flair', 'bueno', 'shier', 'buena', 'dixit', 'eking', 'plods', 'grebe',
'franc', 'frank', 'bleed', 'cured', 'peeve', 'curer', 'cures', 'south', 'whooo', 'whoop',
'facie', 'sadly', 'harum', 'scant', 'natty', 'cabin', 'scans', 'flume', 'nitro', 'negro',
'foamy', 'foams', 'loved', 'prune', 'jocks', 'loves', 'lover', 'wakes', 'waker', 'jinks',
'epees', 'waken', 'sloes', 'parks', 'parka', 'tapis', 'hazed', 'hazel', 'wicks', 'masts',
'hazes', 'hazer', 'darts', 'sedan', 'altos', 'sally', 'gurus', 'gigue', 'beets', 'zonks',
'loams', 'loamy', 'staff', 'swabs', 'areal', 'snits', 'yelps', 'gulch', 'areas', 'crabs',
'drawl', 'kilty', 'organ', 'fixes', 'fixer', 'kilts', 'teams', 'fixed', 'madam', 'trews',
'blats', 'brunt', 'rowan', 'brung', 'janes', 'legit', 'sexed', 'equal', 'lulus', 'agree',
'tater', 'sexes', 'lutes', 'denim', 'luted', 'laugh', 'mafia', 'muddy', 'lepta', 'caddy',
'donee', 'tense', 'kyrie', 'rials', 'homer', 'homes', 'plaid', 'vapid', 'plain', 'homey',
'value', 'plait', 'homed', 'dykes', 'prosy', 'squid', 'squib', 'jelly', 'prose', 'orals',
'whirl', 'diets', 'mimsy', 'dieth', 'infer', 'whirs', 'whirr', 'oleos', 'cubic', 'sauna',
'cubit', 'gloms', 'choos', 'usual', 'unarm', 'unarc', 'nihil', 'unary', 'lossy', 'seats',
'widen', 'raves', 'raver', 'civet', 'vexed', 'bench', 'voile', 'slits', 'raved', 'voila',
'ravel', 'smart', 'raven', 'tests', 'joeys', 'testy', 'twats', 'dryer', 'coypu', 'ozone',
'epoxy', 'chick', 'works', 'moper', 'awash', 'alive', 'axman', 'narco', 'reify', 'faxer',
'shrug', 'trust', 'shrub', 'dunes', 'nimbi', 'tucks', 'panes', 'rumps', 'noise', 'lipid',
'oiled', 'somas', 'paned', 'oiler', 'beaks', 'panel', 'about', 'anded', 'yoyos', 'thuds',
'waifs', 'glade', 'preen', 'flaky', 'evoke', 'glads', 'ropes', 'scums', 'roper', 'unbox',
'zooms', 'socks', 'hexer', 'socko', 'kinda', 'hexed', 'ridge', 'ridgy', 'chunk', 'sicks',
'ivory', 'rajah', 'brand', 'amity', 'rajas', 'brant', 'bhang', 'brans', 'misty', 'glory',
'mists', 'mushy', 'levis', 'groom', 'abeam', 'unsee', 'whoas', 'newsy', 'patsy', 'jeeps',
'homos', 'spivs', 'semis', 'bitsy', 'morns', 'baker', 'bakes', 'pilau', 'hiker', 'hikes',
'wryly', 'pupil', 'baked', 'pilaf', 'roble', 'easts', 'yenta', 'hitch', 'sleet', 'slogs',
'sleep', 'crits', 'tweet', 'cushy', 'under', 'dales', 'pride', 'phial', 'every', 'casas',
'wonts', 'gluey', 'humph', 'humpf', 'gluer', 'glues', 'venue', 'talky', 'clime', 'humpy',
'glued', 'stubs', 'enjoy', 'razed', 'snafu', 'razes', 'razer', 'zests', 'cotes', 'rubes',
'mints', 'prate', 'woozy', 'ramps', 'winey', 'prats', 'enrol', 'forum', 'teaks', 'stray',
'jukes', 'straw', 'gwine', 'stink', 'strap', 'meats', 'ebony', 'meaty', 'assed', 'would',
'idyll', 'spiky', 'bayou', 'asses', 'asset', 'idyls', 'spike', 'saber', 'naive', 'tamps',
'phony', 'grief', 'phone', 'myrrh', 'pouch', 'shoot', 'hutch', 'shoos', 'fakir', 'foils',
'henry', 'hobos', 'shook', 'calve', 'trill', 'agley', 'toxin', 'toxic', 'badly', 'poker',
'pokes', 'befog', 'scion', 'pokey', 'burls', 'poked', 'loppy', 'salsa', 'burly', 'rummy',
'spout', 'rewed', 'enter', 'aloud', 'alack', 'react', 'jerry', 'terns', 'canto', 'howdy',
'tilts', 'edits', 'cants', 'whips', 'bails', 'whipt', 'blots', 'bouts', 'lento', 'gloom',
'toffs', 'fonts', 'chuck', 'choir', 'unapt', 'septa', 'maims', 'sears', 'stogy', 'icers',
'motel', 'motet', 'motes', 'newly', 'oxeye', 'sluff', 'pence', 'bears', 'wowee', 'wowed',
'dunce', 'pyres', 'awoke', 'laxer', 'sober', 'jambs', 'potty', 'degum', 'gowns', 'urban',
'servo', 'serve', 'incur', 'flams', 'roles', 'final', 'flame', 'mirth', 'prone', 'bards',
'pylon', 'leafs', 'ohhhh', 'leafy', 'spade', 'grody', 'hatch', 'cleft', 'rides', 'rider',
'clefs', 'acmes', 'peers', 'soupy', 'soups', 'metal', 'curie', 'curia', 'curio', 'pasha',
'radix', 'queen', 'radii', 'radio', 'queer', 'earth', 'faith', 'spite', 'couth', 'spits',
'anile', 'lodge', 'spitz', 'jeers', 'axiom', 'waltz', 'watch', 'fluid', 'goons', 'goony',
'slags', 'beads', 'apsos', 'beady', 'amide', 'twice', 'erupt', 'shots', 'ruins', 'swept',
'habit', 'wrest', 'wheys', 'inapt', 'rends', 'ailed', 'seder', 'boars', 'adage', 'hokum',
'faced', 'gamed', 'jells', 'fault', 'beeps', 'blimp', 'facet', 'games', 'gamer', 'facer',
'faces', 'jello', 'gamey', 'elfin', 'vexes', 'eying', 'truss', 'bingo', 'aback', 'abaci',
'binge', 'abaca', 'zeals', 'cohos', 'roped', 'board', 'drugs', 'snips', 'craft', 'catch',
'snipe', 'berms', 'auras', 'deeps', 'dells', 'aurae', 'aural', 'broth', 'tress', 'beefy',
'wound', 'pubes', 'lusty', 'moose', 'peaks', 'screw', 'welsh', 'lusts', 'peaky', 'cycle',
'ocean', 'toque', 'torah', 'gilds', 'fiefs', 'vices', 'expos', 'furry', 'steno', 'bandy',
'bands', 'afore', 'judge', 'roach', 'burns', 'burnt', 'befit', 'rumor', 'apart', 'bungs',
'foots', 'feuar', 'ditto', 'swill', 'ditty', 'flaps', 'skoal', 'reams', 'civvy', 'finny',
'scurf', 'zloty', 'pseud', 'usher', 'pulls', 'osier', 'ayins', 'armed', 'rhino', 'loins',
'feted', 'brawl', 'brawn', 'spued', 'fetes', 'gaits', 'shuck', 'bylaw', 'eaves', 'choke',
'caulk', 'cauls', 'curry', 'dials', 'froze', 'civic', 'civil', 'moats', 'guppy', 'stuck',
'clasp', 'crews', 'impro', 'uncle', 'solar', 'furor', 'porks', 'unpin', 'clubs', 'porky',
'twixt', 'prows', 'adore', 'nerdy', 'latch', 'nerds', 'adorn', 'darky', 'darks', 'labia',
'check', 'whorl', 'techs', 'eerie', 'techy', 'junta', 'meows', 'depot', 'tunny', 'muxes',
'preys', 'sacks', 'navel', 'yacht', 'naves', 'weeny', 'coach', 'barfy', 'yokes', 'focus',
'barfs', 'leads', 'yoked', 'yokel', 'guava', 'quasi', 'quash', 'bests', 'tubby', 'sours',
'tanks', 'ritzy', 'level', 'posts', 'levee', 'quick', 'lever', 'poste', 'doeth', 'dries',
'drier', 'trend', 'baled', 'yogis', 'khaki', 'dried', 'bales', 'baler', 'yogic', 'colic',
'croft', 'lodes', 'spire', 'scads', 'axial', 'reply', 'hairy', 'hairs', 'tykes', 'fluky',
'water', 'fluke', 'witch', 'mauls', 'hexad', 'boast', 'culpa', 'weirs', 'molts', 'molto',
'exams', 'prude', 'lamps', 'weird', 'combs', 'snots', 'tweak', 'thrum', 'islet', 'isles',
'bulbs', 'vamps', 'sedge', 'runes', 'bases', 'sedgy', 'dowse', 'today', 'frets', 'lawns',
'altar', 'cased', 'lawny', 'drown', 'beers', 'cases', 'beery', 'sheds', 'fauns', 'radon',
'wands', 'batty', 'fauna', 'trump', 'nexus', 'geeks', 'ousts', 'bigot', 'skims', 'bless',
'vitas', 'alway', 'vitam', 'vital', 'vitae', 'rinks', 'clone', 'rites', 'needs', 'muggy',
'amuse', 'utero', 'needy', 'uteri', 'nonny', 'blare', 'fangs', 'swank', 'lilts', 'leggo',
'hanky', 'hanks', 'swans', 'leggy', 'pomps', 'vails', 'tulip', 'wagon', 'opera', 'belts',
'oared', 'busty', 'busts', 'torch', 'zebra', 'mohel', 'fairs', 'stela', 'stele', 'eagle',
'bolts', 'booby', 'boobs', 'oasis', 'flyer', 'ivies', 'limps', 'flare', 'gusto', 'kneel',
'gusts', 'place', 'swine', 'swing', 'taels', 'gusty', 'oboes', 'feign', 'wiled', 'arras',
'array', 'given', 'whits', 'rayed', 'white', 'circa', 'giver', 'gives', 'schwa', 'suers',
'revue', 'grunt', 'posit', 'chugs', 'bahts', 'mated', 'froth', 'tarts', 'mater', 'mates',
'matey', 'sells', 'ideas', 'ideal', 'malty', 'blunt', 'aspen', 'falls', 'latex', 'annum',
'annul', 'nerfs', 'later', 'pores', 'pengo', 'pored', 'slope', 'perch', 'wooly', 'biers',
'cheap', 'pffft', 'dirge', 'cruds', 'slops', 'nadir', 'desex', 'baric', 'crime', 'skids',
'deign', 'crimp', 'brigs', 'panty', 'wools', 'resew', 'hedge', 'mewed', 'joked', 'cumin',
'naked', 'jokes', 'bison', 'guyed', 'vizor', 'prowl', 'abled', 'fails', 'diode', 'seers',
'nooks', 'nooky', 'bunko', 'summa', 'tikis', 'cafes', 'quiet', 'berry', 'penal', 'bunks',
'cabal', 'color', 'kazoo', 'colon', 'mezzo', 'lifer', 'coupe', 'cordy', 'tesla', 'coups',
'cords', 'flues', 'tiger', 'pilot', 'shaft', 'amend', 'mount', 'twigs', 'loony', 'dorky',
'dorks', 'mound', 'hunts', 'amens', 'numbs', 'parse', 'slomo', 'rungs', 'supra', 'tipsy',
'vower', 'fowls', 'arose', 'vowel', 'vowed', 'giber', 'gibes', 'gamin', 'gamic', 'rupee',
'ranch', 'gibed', 'foyer', 'modem', 'ninth', 'cease', 'manse', 'satin', 'samba', 'seems',
'dully', 'dulls', 'clops', 'roods', 'mahua', 'acute', 'snore', 'towed', 'clays', 'snort',
'friar', 'tower', 'tarot', 'fatwa', 'evade', 'taros', 'oodle', 'slice', 'swaps', 'ashes',
'frees', 'freer', 'divvy', 'slick', 'stops', 'redip', 'nutty', 'bents', 'redid', 'freed',
'diced', 'nails', 'husks', 'pooch', 'dicer', 'dices', 'dicey', 'wader', 'wades', 'raths',
'karat', 'stand', 'waded', 'chive', 'stank', 'knits', 'amber', 'tribe', 'vicar', 'tribs',
'amyls', 'therm', 'there', 'tacts', 'relic', 'burry', 'limns', 'roust', 'burrs', 'burro',
'rouse', 'djinn', 'verve', 'grasp', 'flats', 'ennui', 'grass', 'feued', 'taste', 'intro',
'tasty', 'intra', 'abyss', 'idiot', 'roses', 'besot', 'pappy', 'trash', 'paddy', 'sully',
'brash', 'fetid', 'rutty', 'brass', 'calls', 'curve', 'telex', 'chows', 'curvy', 'calla',
'peeks', 'songs', 'chiff', 'tarry', 'seals', 'kicks', 'voids', 'dairy', 'hulas', 'cress',
'crest', 'lites', 'liter', 'worse', 'soled', 'podgy', 'maced', 'penes', 'awful', 'soles',
'porgy', 'vibes', 'liars', 'flick', 'direr', 'reins', 'whens', 'flics', 'aptly', 'musts',
'ticks', 'crust', 'musty', 'crush', 'musta', 'bries', 'brier', 'cruse', 'yecch', 'fugue',
'avast', 'raked', 'raker', 'rakes', 'naval', 'boded', 'bodes', 'demit', 'texts', 'plonk',
'cooed', 'tutti', 'faint', 'wield', 'frats', 'inlay', 'shits', 'minor', 'seeps', 'waxen',
'deque', 'knows', 'waxed', 'melon', 'stick', 'known', 'waxer', 'waxes', 'ouija', 'berth',
'epics', 'duets', 'arise', 'swung', 'court', 'bawdy', 'tepee', 'mould', 'pupas', 'goopy',
'moult', 'pupae', 'welds', 'pupal', 'shads', 'dorms', 'short', 'shady', 'woosh', 'stash',
'shore', 'barbs', 'shade', 'unhit', 'unhip', 'sloop', 'style', 'glide', 'loxes', 'styli',
'dross', 'asana', 'might', 'alter', 'toves', 'peeps', 'loopy', 'loops', 'sonly', 'kilns',
'fiber', 'quads', 'roofs', 'czars', 'teach', 'frigs', 'noddy', 'exurb', 'fancy', 'sepoy',
'wench', 'soapy', 'ammos', 'soaps', 'story', 'soyas', 'swart', 'grime', 'comfy', 'rails',
'stork', 'swarm', 'storm', 'grimy', 'sward', 'sware', 'swarf', 'syrup', 'store', 'segue',
'boffs', 'hotel', 'rifle', 'boffo', 'uncut', 'chits', 'stall', 'stalk', 'risks', 'stale',
'risky', 'amass', 'vanes', 'exert', 'vaned', 'oaken', 'alike', 'pones', 'moist', 'musos',
'donor', 'banjo', 'added', 'reach', 'rumen', 'adder', 'conic', 'splat', 'grams', 'gushy',
'hyena', 'deans', 'notch', 'lying', 'mimes', 'mimer', 'mimed', 'felon', 'howls', 'mimeo',
'anvil', 'tills', 'mosey', 'fetor', 'gains', 'typos', 'bland', 'wroth', 'wrote', 'vulva',
'stump', 'tarps', 'blurt', 'blurs', 'creme', 'atoll', 'blurb', 'latin', 'wassa', 'rarer',
'condo', 'diked', 'viler', 'roman', 'finds', 'cynic', 'sloth', 'flies', 'flier', 'sweet',
'whelp', 'sweep', 'dudes', 'whelk', 'flied', 'whelm', 'slots', 'acrid', 'goats', 'furls',
'muons', 'brick', 'deice', 'maser', 'cinch', 'shove', 'batch', 'bodge', 'quais', 'leant',
'sirup', 'leans', 'cooch', 'umpty', 'quail', 'shirr', 'viols', 'shirt', 'minim', 'shire',
'viola', 'minis', 'shirk', 'yucca', 'knout', 'flows', 'flown', 'doers', 'birch', 'knack',
'tikes', 'lower', 'sumac', 'cheek', 'dared', 'cheep', 'cheer', 'butyl', 'lowed', 'dares',
'darer', 'frizz', 'wooer', 'pates', 'pater', 'scabs', 'tamed', 'acned', 'kraal', 'tamer',
'tames', 'acnes', 'divot', 'apnea', 'moods', 'moody', 'avows', 'piths', 'cowry', 'punny',
'loggy', 'heath', 'clown', 'yerba', 'attar', 'retry', 'capon', 'capos', 'retro', 'tends',
'mutts', 'casks', 'jumps', 'aloft', 'gigas', 'vivid', 'plaza', 'rangy', 'range', 'modal',
'wanna', 'gamma', 'sudsy', 'mommy', 'johns', 'momma', 'gavel', 'bezel', 'canal', 'sonny',
'whims', 'baggy', 'files', 'filer', 'dados', 'filet', 'clots', 'auric', 'cloth', 'crank',
'usurp', 'filed', 'crane', 'usury', 'seize', 'fries', 'frier', 'fried', 'covet', 'freak',
'soars', 'blahs', 'sepia', 'copra', 'fatso', 'rally', 'rainy', 'lemon', 'peach', 'rains',
'swats', 'peace', 'backs', 'swath', 'sutra', 'users', 'hapax', 'linty', 'kenaf', 'schmo',
'vigil', 'fends', 'lints', 'remix', 'remit', 'karma', 'hooky', 'hooks', 'furze', 'alien',
'windy', 'winds', 'toric', 'cuppy', 'cuppa', 'yeses', 'abode', 'dandy', 'ladle', 'iliac',
'alder', 'spoor', 'spool', 'spoon', 'duffs', 'spook', 'spoof', 'vapes', 'relet', 'notes',
'noter', 'deals', 'dealt', 'outdo', 'noted', 'pleas', 'toils', 'plows', 'pleat', 'folds',
'trawl', 'toile', 'plead', 'acing', 'blobs', 'suets', 'suety', 'imams', 'ginny', 'gaily',
'giant', 'bozos', 'gloat', 'ferry', 'miser', 'weest', 'metro', 'metre', 'apple', 'kudzu',
'whops', 'hardy', 'motor', 'apply', 'smuts', 'porch', 'whang', 'penis', 'women', 'annoy',
'nixed', 'slaps', 'gyros', 'nixes', 'scuzz', 'proof', 'biddy', 'perms', 'crick', 'wizen',
'galls', 'perks', 'serum', 'plyer', 'panic', 'masks', 'perky', 'abuse', 'wrist', 'udder',
'gluts', 'quays', 'light', 'budge', 'theft', 'fizzy', 'looks', 'quake', 'looky', 'minks',
'inlet', 'reeve', 'ships', 'cotta', 'seeth', 'trows', 'crash', 'flour', 'flout', 'crass',
'easel', 'eased', 'feast', 'billy', 'bills', 'eases', 'suras', 'lilac', 'tepid', 'bogey',
'semen', 'chaos', 'grits', 'rheas', 'molls', 'apses', 'pours', 'scoff', 'molly', 'spazz',
'barns', 'ferns', 'hence', 'ionic', 'undid', 'droop', 'their', 'drool', 'mujik', 'shell',
'tuple', 'shelf', 'mules', 'venal', 'muley', 'wanly', 'elope', 'colas', 'gages', 'tommy',
'yodel', 'loots', 'mogul', 'biggy', 'elate', 'betel', 'reeky', 'clove', 'angle', 'scone',
'woofs', 'bough', 'reeks', 'bagel', 'ahold', 'which', 'poxed', 'clash', 'mynas', 'lamed',
'filch', 'mesne', 'delve', 'class', 'lamer', 'lames', 'loges', 'inane', 'goals', 'stove',
'utter', 'slier', 'pawky', 'cache', 'lemma', 'lemme', 'combo', 'piano', 'local', 'vigor',
'skimp', 'klunk', 'heerd', 'gunks', 'words', 'chips', 'gunky', 'yowls', 'wefts', 'ended',
'trued', 'juror', 'cruet', 'trues', 'truer', 'stets', 'rafts', 'expel', 'artsy', 'arses',
'still', 'junks', 'magus', 'banns', 'junky', 'musky', 'favor', 'viper', 'crude', 'theta',
'musks', 'pants', 'lilty', 'spoil', 'swift', 'tiers', 'bronc', 'nabla', 'grain', 'grail',
'bronx', 'abbey', 'rondo', 'ploys', 'table', 'trays', 'jenny', 'amigo', 'hinds', 'tutor',
'shims', 'whams', 'jaded', 'saner', 'jades', 'align', 'beats', 'irate', 'buffa', 'layer',
'motif', 'drips', 'malls', 'snuck', 'whore', 'pooey', 'hocus', 'cross', 'unite', 'unity',
'units', 'spume', 'slave', 'promo', 'beast', 'proms', 'pedal', 'whale', 'lobby', 'antsy',
'gimps', 'twirp', 'gimpy', 'twirl', 'tails', 'eruct', 'cameo', 'cried', 'camel', 'cakes',
'crier', 'cries', 'smite', 'rapid', 'nicks', 'smith', 'hoppy', 'tawny', 'usage', 'enact',
'tizzy', 'press', 'prest', 'feral', 'loser', 'loses', 'hosts', 'diazo', 'merse', 'melee',
'totty', 'stied', 'mines', 'floss', 'noose', 'mined', 'sties', 'trout', 'pasty', 'poets',
'pasts', 'fords', 'pasta', 'fused', 'paste', 'fusee', 'smote', 'urged', 'surge', 'sakes',
'swear', 'sweat', 'urger', 'urges', 'bugle', 'boggy', 'loner', 'soaks', 'champ', 'brush',
'brusk', 'sabra', 'maize', 'sabre', 'sisal', 'pouts', 'fuses', 'beard', 'hilar', 'shank',
'funds', 'deuce', 'below', 'injun', 'begun', 'buffs', 'balsa', 'abbot', 'buffo', 'gizmo',
'glint', 'roars', 'other', 'lance', 'irons', 'kinds', 'mulch', 'sherd', 'pumps', 'mulct',
'kales', 'cliff', 'whump', 'ranks', 'jewel', 'emery', 'xenon']


start = 'thief'
end = 'noose'
queue = new Array()
used[start] = true
st_time = Date.now()
startStack = new Array()
startStack.push(start)
res = createStacks(startStack,queue,used,end,fiveLetterWords)

var cs;
i = 0
while (! res) {
    cs = queue.shift()
    res = createStacks(cs,queue,used,end,fiveLetterWords)
    i++
}
et_time = Date.now()
console.log(res)
console.log(et_time-st_time)